export interface AreaData {
  slug: string;
  name: string;
  county: string;
  description: string;
  population: string;
  distance: string;
  highlights: string[];
}

export const AREAS: AreaData[] = [
  { slug: "pittsburgh", name: "Pittsburgh", county: "Allegheny", description: "As Pittsburgh's premier spray foam insulation provider, we serve the entire city — from Squirrel Hill to the North Side, Shadyside to the South Hills. Pittsburgh's aging housing stock and extreme seasonal temperatures make spray foam the smartest insulation upgrade for city homeowners.", population: "302,000+", distance: "City Center", highlights: ["Historic home retrofit specialists", "Row house and townhome insulation", "Commercial building envelope upgrades"] },
  { slug: "cranberry-township", name: "Cranberry Township", county: "Butler", description: "Cranberry Township's rapid growth means hundreds of homes built in the 2000s with builder-grade fiberglass insulation. These homes are prime candidates for spray foam upgrades that dramatically improve comfort and reduce energy bills.", population: "32,000+", distance: "25 mi north", highlights: ["New construction insulation", "Subdivision energy upgrades", "HOA bulk pricing available"] },
  { slug: "monroeville", name: "Monroeville", county: "Allegheny", description: "Monroeville homeowners know the struggle of keeping 1960s-1980s era homes comfortable. Our spray foam solutions transform these homes — eliminating drafts, reducing noise from Route 22, and cutting energy bills by up to 50%.", population: "28,000+", distance: "13 mi east", highlights: ["Mid-century home insulation experts", "Noise reduction from Route 22", "Commercial plaza insulation"] },
  { slug: "murrysville", name: "Murrysville", county: "Westmoreland", description: "Murrysville's wooded setting and larger homes demand high-performance insulation. Spray foam is the ideal solution for Murrysville's custom homes, providing superior comfort and protection against the area's cold winters.", population: "20,000+", distance: "20 mi east", highlights: ["Custom home insulation", "Large attic and basement projects", "Wooded lot moisture control"] },
  { slug: "bethel-park", name: "Bethel Park", county: "Allegheny", description: "Bethel Park's mix of post-war ranches and split-levels benefit enormously from spray foam insulation. We help South Hills homeowners transform drafty, energy-wasting homes into comfortable, efficient spaces.", population: "33,000+", distance: "10 mi south", highlights: ["Ranch and split-level specialists", "South Hills service area", "Crawl space encapsulation"] },
  { slug: "mount-lebanon", name: "Mount Lebanon", county: "Allegheny", description: "Mount Lebanon's beautiful older homes deserve insulation that preserves their character while delivering modern comfort. Spray foam insulation is applied from inside — no exterior changes, just dramatically better performance.", population: "33,000+", distance: "8 mi south", highlights: ["Historic home preservation", "Minimal aesthetic impact", "Premium residential service"] },
  { slug: "moon-township", name: "Moon Township", county: "Allegheny", description: "From residential neighborhoods to the commercial corridor along University Boulevard, Moon Township benefits from professional spray foam insulation. We serve homeowners and businesses throughout the Airport Corridor.", population: "27,000+", distance: "15 mi west", highlights: ["Airport corridor commercial service", "Residential neighborhood focus", "Industrial facility insulation"] },
  { slug: "north-huntingdon", name: "North Huntingdon", county: "Westmoreland", description: "North Huntingdon's suburban homes face the full force of western PA winters. Spray foam insulation in attics, crawl spaces, and walls makes an immediate difference in comfort and energy costs for North Huntingdon families.", population: "31,000+", distance: "20 mi southeast", highlights: ["Suburban home insulation", "Crawl space solutions", "Energy bill reduction specialists"] },
  { slug: "penn-hills", name: "Penn Hills", county: "Allegheny", description: "Penn Hills is one of Pittsburgh's largest communities, with homes ranging from the 1950s to new construction. Spray foam insulation is the upgrade that makes the biggest impact for Penn Hills homeowners looking to improve comfort and save on energy.", population: "42,000+", distance: "10 mi east", highlights: ["Large community service area", "All home eras and styles", "Affordable insulation upgrades"] },
  { slug: "plum", name: "Plum", county: "Allegheny", description: "Plum Borough homeowners choose spray foam for its unmatched combination of insulation, air sealing, and moisture protection. Our Plum-area projects consistently deliver 40-50% energy savings.", population: "27,000+", distance: "15 mi east", highlights: ["Consistent 40-50% energy savings", "Full-service insulation contractor", "Residential and light commercial"] },
  { slug: "greensburg", name: "Greensburg", county: "Westmoreland", description: "As the Westmoreland County seat, Greensburg has a diverse mix of historic downtown buildings and suburban neighborhoods. We provide spray foam solutions for both residential and commercial properties throughout the Greensburg area.", population: "15,000+", distance: "30 mi southeast", highlights: ["Historic building insulation", "Downtown commercial service", "County-wide coverage"] },
  { slug: "irwin", name: "Irwin", county: "Westmoreland", description: "Irwin and North Irwin homeowners trust us for professional spray foam insulation. Our projects in the Irwin area consistently earn 5-star reviews for quality work, clean installation, and real energy savings.", population: "4,000+", distance: "22 mi southeast", highlights: ["5-star rated service", "Clean, professional installation", "Quick turnaround times"] },
  { slug: "wexford", name: "Wexford", county: "Allegheny", description: "Wexford's upscale homes demand premium insulation performance. Spray foam delivers the comfort, quiet, and efficiency that Wexford homeowners expect — and we deliver the quality installation to match.", population: "12,000+", distance: "18 mi north", highlights: ["Premium home insulation", "Noise reduction solutions", "High-performance building envelope"] },
  { slug: "robinson-township", name: "Robinson Township", county: "Allegheny", description: "Robinson Township's commercial corridor and growing residential areas benefit from professional spray foam insulation. We serve the Settlers Ridge, Summit Park, and surrounding neighborhoods.", population: "15,000+", distance: "12 mi west", highlights: ["Commercial and retail insulation", "Growing residential areas", "Settlers Ridge area service"] },
  { slug: "mccandless", name: "McCandless", county: "Allegheny", description: "McCandless homeowners choose spray foam to combat the area's cold winters and improve home comfort. From the North Hills corridor to residential streets, we deliver expert insulation throughout McCandless.", population: "29,000+", distance: "12 mi north", highlights: ["North Hills service area", "Winter comfort solutions", "Energy-efficient upgrades"] },
  { slug: "export", name: "Export", county: "Westmoreland", description: "Export and the surrounding rural-suburban area benefit from spray foam insulation's superior performance. Larger lots and older homes in Export see dramatic improvements in comfort and energy efficiency.", population: "5,000+", distance: "25 mi east", highlights: ["Rural and suburban homes", "Larger property specialists", "Older home retrofits"] },
  { slug: "delmont", name: "Delmont", county: "Westmoreland", description: "Delmont homeowners in the Route 22 corridor trust our team for professional spray foam insulation. We help Delmont families stay comfortable year-round while reducing energy waste.", population: "3,000+", distance: "28 mi east", highlights: ["Route 22 corridor service", "Family-focused service", "Year-round comfort solutions"] },
  { slug: "latrobe", name: "Latrobe", county: "Westmoreland", description: "From Latrobe's historic neighborhoods to new developments, spray foam insulation delivers the performance edge that western PA homes need. We serve homeowners and businesses throughout the greater Latrobe area.", population: "8,000+", distance: "35 mi southeast", highlights: ["Historic and new home service", "Commercial building insulation", "Extended service area coverage"] },
];

export function getArea(slug: string): AreaData | undefined {
  return AREAS.find((a) => a.slug === slug);
}
